### PR TITLE
Merge upstream

### PR DESCRIPTION
**Pull request by a1batross**
It's me again, bringing you changes from upstream master branch.

No really interesting changes yet, mostly code refactoring, bug fixes, optimizations.
* We finally migrated all cvars to static allocation, making it's easier for CPU to access cvar values. I do not recommend migrating for renderers yet because of known bug with `GLCONFIG` cvars.
* In OpenGL renderer we started to use `GenTextures` call instead of directly binding arbitrary texture IDs, which also fixed few bugs with overlay programs.
* I probably finally fixed the bug where the engine crashes on startup on Linux, somewhere deep in SDL. At least, I haven't seen it for a while.
* We also finally allow C99 code in the engine. I don't think engine will be ported to new old standard overnight, it's just now fine for new code. 
* We support `.pk3dir`. It's a Quake engine's convention to allow mounting directories that end with `.pk3dir`, as if they were archives. It simplifies development process, where current dev version of assets could be in `pk3dir` and packaged into `pk3` for release.
* I added simple tool called `xar` that unpacks data from `.pak`, `.pk3` and `.wad` archives using `filesystem_stdio`.

### CODE REVIEW

**Comment by 0x4E69676874466F78** [comment]
Спасибо!
1. На винде почему-то не собралось.
2. https://github.com/w23/xash3d-fwgs/pull/596/commits/65cc98bf76ce7d9103ebfdf295d2f80cd8f51b0f почему просто не обновить вулкан-сдк на более новый? VulkanSDK-1.3.216.0 уже поддерживает.

**Comment by a1batross** [comment]
2. У меня на рабочей машине вулкан древний, образца начала 2022 года :)

**Comment by a1batross** [comment]
1. Fixed

**Comment by 0x4E69676874466F78** [comment]
Нормально на винде работает.

**Review by w23 — APPROVED** [review]

**Pull request merged**
