### PR TITLE
Sync with upstream

### PR DESCRIPTION
**Pull request by a1batross**
Contains many very important fixes.

### CODE REVIEW

**Comment by a1batross** [comment]
Probably wrong branch. 

@w23 pls change to appropriate branch yourself. Also review RefAPI changes.

**Comment by w23** [comment]
ugh yeah this needs to go into the `better-sampling-passes-parallel` branch. `vulkan` is super stale

**Comment by w23** [comment]
I'm not sure what I'm supposed to do here. Github says this PR says it has conflicts, so I can neither merge it, nor verify that it works (or even builds). Github in its eternal wisdom doesn't even show what the conflicts are (thanks github. Thithub).

The only actionable item for me at this point would be to perform the merge manually myself, which nullifies this PR.

**Comment by w23** [comment]
Had a bit of time, made this: https://github.com/w23/xash3d-fwgs/pull/386

**Pull request closed without merging**
